DATA_DIR = 'data'
CREATE_PROPERTY = "CREATE_PROPERTY"
CREATE_PROPERTY_VALUE = "CREATE_PROPERTY_VALUE"
CREATE_ENTITY = "CREATE_ENTITY" # not sure if this is used
UPDATE_PROPERTY_VALUE = "UPDATE_ENTITY"
DELETE_ENTITY = "DELETE_ENTITY"
DELETE_PROPERTY = "DELETE_PROPERTY"
DELETE_PROPERTY_VALUE = "DELETE_STATEMENT"